### ISSUE TITLE
jcabi-ssh installation

### ISSUE THREAD

**Issue by pmeran** [jcabi/jcabi-ssh#61]
Hi Yegor,
I very much would like to get jcabi-ssh to run. Am very new to Java and networking...

I get some NoClassDefFound error, see further below and attachment.

Is this a version incompatibility between Java and the jar file ?
Using Eclipse Neon.3 release (4.6.3) with Java version 1.8.0_121-b13
jcabi-ssh-1.5.2.jar

Hope you can help - best regards,
Paul

![jcabi-ssh screenshot](https://cloud.githubusercontent.com/assets/28399959/25713704/a13d17dc-30c3-11e7-9b11-4fc8d36bfccf.JPG)

Exception in thread "main" java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException
	at connectPi.isAlive(connectPi.java:14)
	at connectPi.main(connectPi.java:7)
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.JSchException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@pmeran you need to use this JAR instead: http://repo1.maven.org/maven2/com/jcabi/jcabi-ssh/1.5.2/jcabi-ssh-1.5.2-jar-with-dependencies.jar
