### ISSUE TITLE
Jcabi throw java.net.UnknownHostException while all other service can reach my host

### ISSUE THREAD

**Issue by lucas-dehandschutter** [jcabi/jcabi-ssh#76]
I've build a small utility with spring boot that connects to some servers using jcabi-ssh to execute commands.
Here is the class executing the commands:

```
package my.ssh.utility;

import com.jcabi.ssh.Shell;
import com.jcabi.ssh.Ssh;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.util.Optional;

@Service
public class SshExecutorImpl implements SshExecutor {

    private static final Logger LOG = LoggerFactory.getLogger(SshExecutorImpl.class);

    private String sshUser;

    private String sshKey;

    @Value("${ssh-user}")
    public void setSshUser(String sshUser) {
        this.sshUser = sshUser;
    }

    @Value("${ssh-key}")
    public void setSshKey(String sshKey) {
        this.sshKey = sshKey;
    }

    @Override
    public String execute(String hostname, String command) throws IOException {

        Optional<String> response = Optional.ofNullable(new Shell.Plain(
                new Ssh(hostname, 22,
                        sshUser, sshKey
                )
        ).exec(command));
        return response.orElseThrow(IOException::new);
    }
}
```
This applications is package in a docker image and is run using the following command in the container:

```
#!/bin/sh
exec java -Djava.security.egd=file:/dev/./urandom -jar app.jar --spring.config.location=file:./config/secrets.yml,classpath:/

```
The docker image is run as a docker service and all servers i have to access to are specified using the --host parameter. If i connect to my container and check the /etc/hosts file, i get the following:

```
127.0.0.1       localhost                                                                                                
::1     localhost ip6-localhost ip6-loopback                                                                             
fe00::0 ip6-localnet                                                                                                     
ff00::0 ip6-mcastprefix                                                                                                  
ff02::1 ip6-allnodes                                                                                                     
ff02::2 ip6-allrouters                                                                                                   
192.168.1.100     myserver1.mycompany.com                                                                                       
192.168.1.101     myserver2.mycompany.com                                                                             
192.168.1.102     myserver3.mycompany.com                                                                                        
192.168.1.103     myserver4.mycompany.com                                                                                        
192.168.1.104     myserver5.mycompany.com                                                                                        
192.168.1.105     myserver6.mycompany.com                                                                                      
192.168.1.106     myserver7.mycompany.com  
```
While this container ( started with a simple docker run ...) worked well on my own test environment i get the following error on the target environment ( with a docker service create ... )

```
.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]                                
optimistic_swirles.1.5slbc2ehoit8@node1    |        at org.springframework.scheduling.support.DelegatingErrorHandling
Runnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]                
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(
Executors.java:514) [na:na]                                                                                              
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTa
sk.java:305) [na:na]                                                                                                     
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$Sch
eduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [na:na]                                                       
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Th
readPoolExecutor.java:1135) [na:na]                                                                                      
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(T
hreadPoolExecutor.java:635) [na:na]                                                                                      
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.lang.Thread.run(Thread.java:844) [na:na]       
optimistic_swirles.1.5slbc2ehoit8@node1    | Caused by: java.net.UnknownHostException:  myserver1.mycompany.com: Name or se
rvice not known                                                                                                          
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native M
ethod) ~[na:na]                                                                                                          
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHo
stAddr(InetAddress.java:925) ~[na:na]                                                                                    
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.InetAddress.getAddressesFromNameService(Ine
tAddress.java:1505) ~[na:na]                                                                                             
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAd
dress.java:844) ~[na:na]                                                                                                 
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:
1495) ~[na:na]                                                                                                           
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1
354) ~[na:na]                                                                                                            
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1
288) ~[na:na]                                                                                                            
optimistic_swirles.1.5slbc2ehoit8@node1    |        at java.base/java.net.InetAddress.getByName(InetAddress.java:1238
) ~[na:na]                                                                                                               
optimistic_swirles.1.5slbc2ehoit8@node1    |        at com.jcabi.ssh.AbstractSshShell.<init>(AbstractSshShell.java:80
) ~[jcabi-ssh-1.6.jar!/:na]                                                                                              
optimistic_swirles.1.5slbc2ehoit8@node1    |        at com.jcabi.ssh.Ssh.<init>(Ssh.java:215) ~[jcabi-ssh-1.6.jar!/:n
a]                                                                                                                       
optimistic_swirles.1.5slbc2ehoit8@node1    |        at com.jcabi.ssh.Ssh.<init>(Ssh.java:198) ~[jcabi-ssh-1.6.jar!/:n
a]                                                                                                                       
optimistic_swirles.1.5slbc2ehoit8@node1    |        at 
my.ssh.utility.SshExecutorImpl.execute(SshExe
cutorImpl.java:35) ~[classes!/:0.0.1-SNAPSHOT]   
```
Within my docker container using the bash command, I can reach myserver1 with several tools such as netcat or ping and i can also directly ssh myserver1 using the docker host server. So i'm pretty sure this is not a firewall issue nor a network configuration mismatch inside my container.

Do you have any idea on what's causing this issue?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@lucas-dehandschutter[/z](https://www.0crat.com/u/lucas-dehandschutter) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@lucas-dehandschutter seems to be a mistake in the host name:

```
Caused by: java.net.UnknownHostException:  myserver1.mycompany.com
```

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#76` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
