### ISSUE TITLE
Upgrade the cactoos dependency to the latest version as they are incompatible now

### ISSUE THREAD

**Issue by dgroup** [jcabi/jcabi-ssh#84]
```java
java.lang.NoClassDefFoundError: org/cactoos/io/LengthOf

	at com.jcabi.ssh.Ssh.session(Ssh.java:246)
	at com.jcabi.ssh.AbstractSshShell.exec(AbstractSshShell.java:95)
	at com.jcabi.ssh.Ssh.exec(Ssh.java:77)
	at com.jcabi.ssh.Shell$Plain.exec(Shell.java:241)
```
Latest version for now is `0.41`.
The current version within jcabi-ssh is `0.16`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9V6HBZQS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
